### ISSUE TITLE
Error: Could not load email provider "msgraph"

### ISSUE THREAD

**Issue by iantrudell** [mondago/strapi-provider-email-msgraph#7]
In Strapi v4, I am getting this error:

Error: Could not load email provider "msgraph".                            â”‚â”‚   at createProvider                                                          â”‚â”‚   (/node_modules/@strapi/plugin-email/dist/server/index.js:40:11)            â”‚â”‚   at Object.bootstrap                                                        â”‚â”‚   (/node_modules/@strapi/plugin-email/dist/server/index.js:46:38)            â”‚â”‚   at Object.bootstrap                                                        â”‚â”‚   (/node_modules/@strapi/strapi/dist/core/domain/module/index.js:39:47)      â”‚â”‚   at Object.bootstrap                                                        â”‚â”‚   (/node_modules/@strapi/strapi/dist/core/registries/modules.js:23:19)       â”‚â”‚   at process.processTicksAndRejections                                       â”‚â”‚   (node:internal/process/task_queues:95:5)                                   â”‚â”‚   at async Strapi.runLifecyclesFunctions                                     â”‚â”‚   (/node_modules/@strapi/strapi/dist/Strapi.js:440:5)                        â”‚â”‚   at async Strapi.bootstrap                                                  â”‚â”‚   (/node_modules/@strapi/strapi/dist/Strapi.js:420:5)                        â”‚â”‚   at async Strapi.load (/node_modules/@strapi/strapi/dist/Strapi.js:426:5)   â”‚â”‚   at async Object.develop                                                    â”‚â”‚   (/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:837:28)        â”‚â”‚   at async develop                                                           â”‚â”‚   (/node_modules/@strapi/admin/dist/_chunks/develop-YNTGWKMC.js:61:5)        â”‚â”‚

**config.ts:**
```
export default ({ env }) => ({
    email: {
        config: {
            provider: "msgraph",
            providerOptions: {
                clientId: env("MSGRAPH_CLIENT_ID"),
                clientSecret: env("MSGRAPH_SECRET"),
                tenantId: env("MSGRAPH_TENANT"),
            },
            settings: {
                defaultFrom: env("MSGRAPH_FROM"),
            },
        },
    },
});
```

**Comment by iantrudell** [comment]
Did a little digging, it may have to do with the Strapi v4 changes described here:
https://github.com/ijsto/strapi-provider-email-postmark#example
and here:
https://github.com/strapi/strapi/issues/11879
```
IMPORTANT: With Strapi v4, you have to set email.config.provider to "strapi-provider-email-msgraph", instead of "msgraph". This is intended in Strapi v4: https://github.com/strapi/strapi/issues/11879.

Additionally, the structure of plugins.js has changed:

In v3: "email": {"provider": "", ...}
In v4: "email": {"config": {"provider": "", ...}}
```

**Comment by dnlyates** [comment]
Apologies, yes the documentation is wrong. The provider should be set to `strapi-provider-email-msgraph` and not `msgraph`.
